### ISSUE TITLE
Didn't undertand the use of these lines

### ISSUE THREAD

**Issue by frezbo** [iann0036/aws-account-controller#2]
I was going through the code and there was this part I didn't quite catch:
https://github.com/iann0036/aws-account-controller/blob/master/lambda/index.js#L407-L412

What's the use of `certificate.pem`? Is it something generated as part of SSO app creation?

**Comment by iann0036** [comment]
> Is it something generated as part of SSO app creation?

Yes, that's correct.

The certificate is downloaded from SSO during app creation [here](https://github.com/iann0036/aws-account-controller/blob/master/lambda/index.js#L372-L373) and is somewhat explained [in these AWS docs](https://docs.aws.amazon.com/singlesignon/latest/userguide/managecerts.html).

The certificate is downloaded and stored to ensure that requests made using the SSO app by users is valid.

**Comment by frezbo** [comment]
Awesome, Thanks for the clarification. I will close this out.
